/***************************************************************************//**
 * @file  zap-enabled-incoming-commands.h
 * @brief This file contains a set of macros for all the cluster commands which
 have incoming enabled.
 * This file is generated. Do not update file manually.
 *******************************************************************************
 * # License
 * <b>Copyright 2020 Silicon Laboratories Inc. www.silabs.com</b>
 *******************************************************************************
 *
 * The licensor of this software is Silicon Laboratories Inc. Your use of this
 * software is governed by the terms of Silicon Labs Master Software License
 * Agreement (MSLA) available at
 * www.silabs.com/about-us/legal/master-software-license-agreement. This
 * software is distributed to you in Source Code format and is governed by the
 * sections of the MSLA applicable to Source Code.
 *
 ******************************************************************************/
#define ZCL_CLUSTER_BASIC_SERVER_INCOMING_COMMAND_RESET_TO_FACTORY_DEFAULTS_ENABLED
#define ZCL_CLUSTER_COLOR_CONTROL_SERVER_INCOMING_COMMAND_MOVE_TO_HUE_ENABLED
#define ZCL_CLUSTER_COLOR_CONTROL_SERVER_INCOMING_COMMAND_MOVE_HUE_ENABLED
#define ZCL_CLUSTER_COLOR_CONTROL_SERVER_INCOMING_COMMAND_STEP_HUE_ENABLED
#define ZCL_CLUSTER_COLOR_CONTROL_SERVER_INCOMING_COMMAND_MOVE_TO_SATURATION_ENABLED
#define ZCL_CLUSTER_COLOR_CONTROL_SERVER_INCOMING_COMMAND_MOVE_SATURATION_ENABLED
#define ZCL_CLUSTER_COLOR_CONTROL_SERVER_INCOMING_COMMAND_STEP_SATURATION_ENABLED
#define ZCL_CLUSTER_COLOR_CONTROL_SERVER_INCOMING_COMMAND_MOVE_TO_HUE_AND_SATURATION_ENABLED
#define ZCL_CLUSTER_COLOR_CONTROL_SERVER_INCOMING_COMMAND_MOVE_TO_COLOR_ENABLED
#define ZCL_CLUSTER_COLOR_CONTROL_SERVER_INCOMING_COMMAND_MOVE_COLOR_ENABLED
#define ZCL_CLUSTER_COLOR_CONTROL_SERVER_INCOMING_COMMAND_STEP_COLOR_ENABLED
#define ZCL_CLUSTER_COLOR_CONTROL_SERVER_INCOMING_COMMAND_MOVE_TO_COLOR_TEMPERATURE_ENABLED
#define ZCL_CLUSTER_COLOR_CONTROL_SERVER_INCOMING_COMMAND_ENHANCED_MOVE_TO_HUE_ENABLED
#define ZCL_CLUSTER_COLOR_CONTROL_SERVER_INCOMING_COMMAND_ENHANCED_MOVE_HUE_ENABLED
#define ZCL_CLUSTER_COLOR_CONTROL_SERVER_INCOMING_COMMAND_ENHANCED_STEP_HUE_ENABLED
#define ZCL_CLUSTER_COLOR_CONTROL_SERVER_INCOMING_COMMAND_ENHANCED_MOVE_TO_HUE_AND_SATURATION_ENABLED
#define ZCL_CLUSTER_COLOR_CONTROL_SERVER_INCOMING_COMMAND_COLOR_LOOP_SET_ENABLED
#define ZCL_CLUSTER_COLOR_CONTROL_SERVER_INCOMING_COMMAND_STOP_MOVE_STEP_ENABLED
#define ZCL_CLUSTER_COLOR_CONTROL_SERVER_INCOMING_COMMAND_MOVE_COLOR_TEMPERATURE_ENABLED
#define ZCL_CLUSTER_COLOR_CONTROL_SERVER_INCOMING_COMMAND_STEP_COLOR_TEMPERATURE_ENABLED
#define ZCL_CLUSTER_GREEN_POWER_CLIENT_INCOMING_COMMAND_GP_PAIRING_ENABLED
#define ZCL_CLUSTER_GREEN_POWER_CLIENT_INCOMING_COMMAND_GP_PROXY_COMMISSIONING_MODE_ENABLED
#define ZCL_CLUSTER_GREEN_POWER_CLIENT_INCOMING_COMMAND_GP_RESPONSE_ENABLED
#define ZCL_CLUSTER_GREEN_POWER_CLIENT_INCOMING_COMMAND_GP_PROXY_TABLE_REQUEST_ENABLED
#define ZCL_CLUSTER_GROUPS_SERVER_INCOMING_COMMAND_ADD_GROUP_ENABLED
#define ZCL_CLUSTER_GROUPS_SERVER_INCOMING_COMMAND_VIEW_GROUP_ENABLED
#define ZCL_CLUSTER_GROUPS_SERVER_INCOMING_COMMAND_GET_GROUP_MEMBERSHIP_ENABLED
#define ZCL_CLUSTER_GROUPS_SERVER_INCOMING_COMMAND_REMOVE_GROUP_ENABLED
#define ZCL_CLUSTER_GROUPS_SERVER_INCOMING_COMMAND_REMOVE_ALL_GROUPS_ENABLED
#define ZCL_CLUSTER_GROUPS_SERVER_INCOMING_COMMAND_ADD_GROUP_IF_IDENTIFYING_ENABLED
#define ZCL_CLUSTER_IDENTIFY_SERVER_INCOMING_COMMAND_IDENTIFY_ENABLED
#define ZCL_CLUSTER_IDENTIFY_SERVER_INCOMING_COMMAND_IDENTIFY_QUERY_ENABLED
#define ZCL_CLUSTER_IDENTIFY_SERVER_INCOMING_COMMAND_TRIGGER_EFFECT_ENABLED
#define ZCL_CLUSTER_LEVEL_CONTROL_SERVER_INCOMING_COMMAND_MOVE_TO_LEVEL_ENABLED
#define ZCL_CLUSTER_LEVEL_CONTROL_SERVER_INCOMING_COMMAND_MOVE_ENABLED
#define ZCL_CLUSTER_LEVEL_CONTROL_SERVER_INCOMING_COMMAND_STEP_ENABLED
#define ZCL_CLUSTER_LEVEL_CONTROL_SERVER_INCOMING_COMMAND_STOP_ENABLED
#define ZCL_CLUSTER_LEVEL_CONTROL_SERVER_INCOMING_COMMAND_MOVE_TO_LEVEL_WITH_ON_OFF_ENABLED
#define ZCL_CLUSTER_LEVEL_CONTROL_SERVER_INCOMING_COMMAND_MOVE_WITH_ON_OFF_ENABLED
#define ZCL_CLUSTER_LEVEL_CONTROL_SERVER_INCOMING_COMMAND_STEP_WITH_ON_OFF_ENABLED
#define ZCL_CLUSTER_LEVEL_CONTROL_SERVER_INCOMING_COMMAND_STOP_WITH_ON_OFF_ENABLED
#define ZCL_CLUSTER_ON_OFF_SERVER_INCOMING_COMMAND_OFF_ENABLED
#define ZCL_CLUSTER_ON_OFF_SERVER_INCOMING_COMMAND_ON_ENABLED
#define ZCL_CLUSTER_ON_OFF_SERVER_INCOMING_COMMAND_TOGGLE_ENABLED
#define ZCL_CLUSTER_ON_OFF_SERVER_INCOMING_COMMAND_OFF_WITH_EFFECT_ENABLED
#define ZCL_CLUSTER_ON_OFF_SERVER_INCOMING_COMMAND_ON_WITH_RECALL_GLOBAL_SCENE_ENABLED
#define ZCL_CLUSTER_ON_OFF_SERVER_INCOMING_COMMAND_ON_WITH_TIMED_OFF_ENABLED
#define ZCL_CLUSTER_SCENES_SERVER_INCOMING_COMMAND_ADD_SCENE_ENABLED
#define ZCL_CLUSTER_SCENES_SERVER_INCOMING_COMMAND_VIEW_SCENE_ENABLED
#define ZCL_CLUSTER_SCENES_SERVER_INCOMING_COMMAND_REMOVE_SCENE_ENABLED
#define ZCL_CLUSTER_SCENES_SERVER_INCOMING_COMMAND_REMOVE_ALL_SCENES_ENABLED
#define ZCL_CLUSTER_SCENES_SERVER_INCOMING_COMMAND_STORE_SCENE_ENABLED
#define ZCL_CLUSTER_SCENES_SERVER_INCOMING_COMMAND_RECALL_SCENE_ENABLED
#define ZCL_CLUSTER_SCENES_SERVER_INCOMING_COMMAND_GET_SCENE_MEMBERSHIP_ENABLED
#define ZCL_CLUSTER_SCENES_SERVER_INCOMING_COMMAND_ENHANCED_ADD_SCENE_ENABLED
#define ZCL_CLUSTER_SCENES_SERVER_INCOMING_COMMAND_ENHANCED_VIEW_SCENE_ENABLED
#define ZCL_CLUSTER_SCENES_SERVER_INCOMING_COMMAND_COPY_SCENE_ENABLED
#define ZCL_CLUSTER_ZLL_COMMISSIONING_SERVER_INCOMING_COMMAND_SCAN_REQUEST_ENABLED
#define ZCL_CLUSTER_ZLL_COMMISSIONING_SERVER_INCOMING_COMMAND_DEVICE_INFORMATION_REQUEST_ENABLED
#define ZCL_CLUSTER_ZLL_COMMISSIONING_SERVER_INCOMING_COMMAND_IDENTIFY_REQUEST_ENABLED
#define ZCL_CLUSTER_ZLL_COMMISSIONING_SERVER_INCOMING_COMMAND_RESET_TO_FACTORY_NEW_REQUEST_ENABLED
#define ZCL_CLUSTER_ZLL_COMMISSIONING_SERVER_INCOMING_COMMAND_NETWORK_START_REQUEST_ENABLED
#define ZCL_CLUSTER_ZLL_COMMISSIONING_SERVER_INCOMING_COMMAND_NETWORK_JOIN_ROUTER_REQUEST_ENABLED
#define ZCL_CLUSTER_ZLL_COMMISSIONING_SERVER_INCOMING_COMMAND_NETWORK_JOIN_END_DEVICE_REQUEST_ENABLED
#define ZCL_CLUSTER_ZLL_COMMISSIONING_SERVER_INCOMING_COMMAND_NETWORK_UPDATE_REQUEST_ENABLED
#define ZCL_CLUSTER_ZLL_COMMISSIONING_SERVER_INCOMING_COMMAND_GET_GROUP_IDENTIFIERS_REQUEST_ENABLED
#define ZCL_CLUSTER_ZLL_COMMISSIONING_SERVER_INCOMING_COMMAND_GET_ENDPOINT_LIST_REQUEST_ENABLED
