################################################################################
# Automatically-generated file. Do not edit!
################################################################################

S79_SRCS := 
OBJ_SRCS := 
S_SRCS := 
ASM_SRCS := 
C_SRCS := 
S79_UPPER_SRCS := 
S_UPPER_SRCS := 
O_SRCS := 
EXECUTABLES := 
OBJS := 
C_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
. \
autogen \
gecko_sdk_4.4.3/app/bluetooth/common/sensor_rht \
gecko_sdk_4.4.3/app/bluetooth/common/sensor_select \
gecko_sdk_4.4.3/hardware/board/src \
gecko_sdk_4.4.3/hardware/driver/configuration_over_swo/src \
gecko_sdk_4.4.3/hardware/driver/mx25_flash_shutdown/src/sl_mx25_flash_shutdown_usart \
gecko_sdk_4.4.3/hardware/driver/si70xx/src \
gecko_sdk_4.4.3/platform/Device/SiliconLabs/EFR32MG24/Source \
gecko_sdk_4.4.3/platform/bootloader/api \
gecko_sdk_4.4.3/platform/bootloader/app_properties \
gecko_sdk_4.4.3/platform/common/src \
gecko_sdk_4.4.3/platform/common/toolchain/src \
gecko_sdk_4.4.3/platform/driver/button/src \
gecko_sdk_4.4.3/platform/driver/debug/src \
gecko_sdk_4.4.3/platform/driver/i2cspm/src \
gecko_sdk_4.4.3/platform/driver/leddrv/src \
gecko_sdk_4.4.3/platform/emdrv/dmadrv/src \
gecko_sdk_4.4.3/platform/emdrv/gpiointerrupt/src \
gecko_sdk_4.4.3/platform/emdrv/nvm3/src \
gecko_sdk_4.4.3/platform/emlib/src \
gecko_sdk_4.4.3/platform/peripheral/src \
gecko_sdk_4.4.3/platform/radio/rail_lib/plugin/coexistence/protocol/ieee802154_uc \
gecko_sdk_4.4.3/platform/radio/rail_lib/plugin/pa-conversions \
gecko_sdk_4.4.3/platform/radio/rail_lib/plugin/rail_util_ant_div \
gecko_sdk_4.4.3/platform/radio/rail_lib/plugin/rail_util_built_in_phys/efr32xg24 \
gecko_sdk_4.4.3/platform/radio/rail_lib/plugin/rail_util_built_in_phys \
gecko_sdk_4.4.3/platform/radio/rail_lib/plugin/rail_util_power_manager_init \
gecko_sdk_4.4.3/platform/radio/rail_lib/plugin/rail_util_pti \
gecko_sdk_4.4.3/platform/radio/rail_lib/plugin/rail_util_sequencer \
gecko_sdk_4.4.3/platform/security/sl_component/se_manager/src \
gecko_sdk_4.4.3/platform/security/sl_component/sl_mbedtls_support/src \
gecko_sdk_4.4.3/platform/security/sl_component/sl_psa_driver/src \
gecko_sdk_4.4.3/platform/service/cli/src \
gecko_sdk_4.4.3/platform/service/device_init/src \
gecko_sdk_4.4.3/platform/service/hfxo_manager/src \
gecko_sdk_4.4.3/platform/service/iostream/src \
gecko_sdk_4.4.3/platform/service/legacy_hal/src \
gecko_sdk_4.4.3/platform/service/legacy_hal_wdog/src \
gecko_sdk_4.4.3/platform/service/legacy_printf/src \
gecko_sdk_4.4.3/platform/service/power_manager/src \
gecko_sdk_4.4.3/platform/service/sleeptimer/src \
gecko_sdk_4.4.3/platform/service/system/src \
gecko_sdk_4.4.3/platform/service/token_manager/src \
gecko_sdk_4.4.3/platform/service/udelay/src \
gecko_sdk_4.4.3/protocol/zigbee/app/framework/cli \
gecko_sdk_4.4.3/protocol/zigbee/app/framework/common \
gecko_sdk_4.4.3/protocol/zigbee/app/framework/plugin/basic \
gecko_sdk_4.4.3/protocol/zigbee/app/framework/plugin/color-control-server \
gecko_sdk_4.4.3/protocol/zigbee/app/framework/plugin/counters \
gecko_sdk_4.4.3/protocol/zigbee/app/framework/plugin/debug-print \
gecko_sdk_4.4.3/protocol/zigbee/app/framework/plugin/find-and-bind-target \
gecko_sdk_4.4.3/protocol/zigbee/app/framework/plugin/green-power-client \
gecko_sdk_4.4.3/protocol/zigbee/app/framework/plugin/green-power-common \
gecko_sdk_4.4.3/protocol/zigbee/app/framework/plugin/groups-server \
gecko_sdk_4.4.3/protocol/zigbee/app/framework/plugin/identify \
gecko_sdk_4.4.3/protocol/zigbee/app/framework/plugin/interpan \
gecko_sdk_4.4.3/protocol/zigbee/app/framework/plugin/level-control \
gecko_sdk_4.4.3/protocol/zigbee/app/framework/plugin/network-creator \
gecko_sdk_4.4.3/protocol/zigbee/app/framework/plugin/network-creator-security \
gecko_sdk_4.4.3/protocol/zigbee/app/framework/plugin/network-steering \
gecko_sdk_4.4.3/protocol/zigbee/app/framework/plugin/on-off \
gecko_sdk_4.4.3/protocol/zigbee/app/framework/plugin/reporting \
gecko_sdk_4.4.3/protocol/zigbee/app/framework/plugin/scan-dispatch \
gecko_sdk_4.4.3/protocol/zigbee/app/framework/plugin/scenes \
gecko_sdk_4.4.3/protocol/zigbee/app/framework/plugin/stack-diagnostics \
gecko_sdk_4.4.3/protocol/zigbee/app/framework/plugin/update-tc-link-key \
gecko_sdk_4.4.3/protocol/zigbee/app/framework/plugin/zcl_cli \
gecko_sdk_4.4.3/protocol/zigbee/app/framework/plugin/zll-commissioning-common \
gecko_sdk_4.4.3/protocol/zigbee/app/framework/plugin/zll-commissioning-server \
gecko_sdk_4.4.3/protocol/zigbee/app/framework/plugin/zll-identify-server \
gecko_sdk_4.4.3/protocol/zigbee/app/framework/plugin/zll-level-control-server \
gecko_sdk_4.4.3/protocol/zigbee/app/framework/plugin/zll-on-off-server \
gecko_sdk_4.4.3/protocol/zigbee/app/framework/plugin/zll-scenes-server \
gecko_sdk_4.4.3/protocol/zigbee/app/framework/plugin/zll-utility-server \
gecko_sdk_4.4.3/protocol/zigbee/app/framework/security \
gecko_sdk_4.4.3/protocol/zigbee/app/framework/service-function \
gecko_sdk_4.4.3/protocol/zigbee/app/framework/signature-decode \
gecko_sdk_4.4.3/protocol/zigbee/app/framework/util \
gecko_sdk_4.4.3/protocol/zigbee/app/util/common \
gecko_sdk_4.4.3/protocol/zigbee/app/util/security \
gecko_sdk_4.4.3/protocol/zigbee/app/util/serial \
gecko_sdk_4.4.3/protocol/zigbee/app/util/zigbee-framework \
gecko_sdk_4.4.3/protocol/zigbee/stack/config \
gecko_sdk_4.4.3/protocol/zigbee/stack/core \
gecko_sdk_4.4.3/protocol/zigbee/stack/framework \
gecko_sdk_4.4.3/protocol/zigbee/stack/mac \
gecko_sdk_4.4.3/protocol/zigbee/stack/routing/zigbee \
gecko_sdk_4.4.3/protocol/zigbee/stack/security \
gecko_sdk_4.4.3/protocol/zigbee/stack/stubs \
gecko_sdk_4.4.3/protocol/zigbee/stack/zigbee \
gecko_sdk_4.4.3/util/plugin/security_manager \
gecko_sdk_4.4.3/util/silicon_labs/silabs_core/memory_manager \
gecko_sdk_4.4.3/util/third_party/mbedtls/library \
gecko_sdk_4.4.3/util/third_party/printf \
gecko_sdk_4.4.3/util/third_party/printf/src \

